import { priority } from "./utils";
export const todoData = [
    {
        id: 1,
        todo: 'this is a todo',
        description: 'this is a todo description',
        priority: priority.HIGH,
        dueDate: new Date('23, May, 2024'),
        createdBy: 10123,
        assignedTo: 10123,
        isActive: true,
        isCompleted: false,
    },
    {
        id: 2,
        todo: 'this is a todo 1',
        description: 'this is a todo description',
        priority: priority.HIGH,
        dueDate: new Date('17, May, 2024'),
        createdBy: 10124,
        assignedTo: 10123,
        isActive: true,
        isCompleted: false,
    },
    {
        id: 3,
        todo: 'this is a todo 2',
        description: 'this is a todo description',
        priority: priority.MEDIUM,
        dueDate: new Date('17, May, 2024'),
        createdBy: 10124,
        assignedTo: 10124,
        isActive: true,
        isCompleted: false,
    },
    {
        id: 4,
        todo: 'this is a todo 3',
        description: 'this is a todo description',
        priority: priority.LOW,
        dueDate: new Date('17, May, 2024'),
        createdBy: 10124,
        assignedTo: 10124,
        isActive: true,
        isCompleted: false,
    },
    {
        id: 5,
        todo: 'this is a todo 4',
        description: 'this is a todo description',
        priority: priority.MEDIUM,
        dueDate: new Date('20, May, 2024'),
        createdBy: 10124,
        assignedTo: 10124,
        isActive: true,
        isCompleted: false,
    },
    {
        id: 6,
        todo: 'this is a todo 5',
        description: 'this is a todo description',
        priority: priority.LOW,
        dueDate: new Date('23, May, 2024'),
        createdBy: 10123,
        assignedTo: 10124,
        isActive: true,
        isCompleted: false,
    }
]